import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  //   docsSidebar: [
  //     "intro",
  //     // "hello",
  //     {
  //       type: "category",
  //       label: "Tutorial",
  //       items: ["tutorial-basics/create-a-document"],
  //     },
  //   ],
};

export default sidebars;
